[package]
name = "most_common_bits"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/zperk13/most_common_bits"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
